services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  front-end:
    container_name: htb-web
    image: node
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api.htb.v34l.com
      - VITE_API_PORT=5000
      - VITE_WEBSOCKET_URL=ws://ws.htb.v34l.com
      - VITE_WEBSOCKET_PORT=8990
    volumes:
      - ./htb-frontend:/htb-frontend 
    command: >
      sh -c "cd /htb-frontend &&
             npm install &&
             npm run dev -- --host"

  websocket:
    container_name: htb-ws
    image: node
    ports:
      - "8990:8990"
    environment:
      - WEBSOCKET_PORT=8990
    volumes:
      - ./websocket:/websocket
    command: >
      sh -c "cd /htb-ws &&
             npm install &&
             node index.js"
             
  api:
    container_name: htb-api
    image: python
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    volumes:
      - ./api/static/uploads:/api/static/uploads
      - ./api:/api
      
    command: >
      sh -c "cd /htb-api &&
             python -m venv .venv &&
             . .venv/bin/activate &&
             pip install -r requirements.txt &&
             gunicorn -w 4 -b 0.0.0.0:5000 app.app:app"
