services:
  setup:
    command:  >
      sh -c "if [ -e ./.env ]; then
      echo "File exists"
      else
      cp env-example .env
      fi
      cp env. htb-frontend/.env
      cp .env api/.env
      cp .env websocket/.env"
      
  redis:
    container_name: htb-redis
    image: redis
    ports:
      - "3033:3033"

  front-end:
    container_name: htb-web
    image: node
    ports:
      - "8080:80"
    command: >
      sh -c "cd htb-frontend &&
             npm install &&
             npm run dev -- --host"

  websocket:
    container_name: htb-ws
    image: node
    ports:
      - "8990:8990"
    command: >
      sh -c "cd websocket &&
             npm install &&
             node index.js"

  api:
    container_name: htb-api
    image: python
    ports:
      - "5000:5000"
    command: >
      sh -c "cd api &&
             python -m venv .venv &&
             . .venv/bin/activate &&
             pip install -r requirements.txt &&
             flask run --host=0.0.0.0"
