services:
  setup:
    image: alpine
    container_name: setup-container
    command:  >
      sh -c "if [ ! -e ./.env ]; then
      cp env-example .env
      fi &&
      cp .env htb-frontend/.env &&
      cp .env api/.env &&
      cp .env websocket/.env"
      
  redis:
    container_name: htb-redis
    image: redis
    ports:
      - "6379:6379"

  front-end:
    container_name: htb-web
    image: node
    ports:
      - "8080:80"
    volumes:
      - ./htb-frontend:/htb-frontend 
    command: >
      sh -c "cd /htb-frontend &&
             npm install &&
             npm run dev -- --host"

  websocket:
    container_name: htb-ws
    image: node
    ports:
      - "8990:8990"
    volumes:
      - ./websocket:/websocket
    command: >
      sh -c "cd /websocket &&
             npm install &&
             node index.js"

  api:
    container_name: htb-api
    image: python
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    command: >
      sh -c "cd /api &&
             python -m venv .venv &&
             . .venv/bin/activate &&
             pip install -r requirements.txt &&
             flask run --host=0.0.0.0"
