networks:
  htb:
    driver: bridge

services:    
  redis:
    container_name: htb-redis
    image: redis
    command: redis-server --bind 0.0.0.0 --protected-mode yes
    ports:
      - "6379:6379"
    networks:
      - htb

  front-end:
    container_name: htb-web
    image: node
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://htb-api
      - VITE_API_PORT=5000
      - VITE_WEBSOCKET_URL=ws://htb-ws
      - VITE_WEBSOCKET_PORT=8990
    networks:
      - htb
    volumes:
      - ./htb-frontend:/htb-frontend 
    command: >
      sh -c "cd /htb-frontend &&
             npm audit fix &&
             npm install &&
             npm run dev -- --host"

  websocket:
    container_name: htb-ws
    image: node
    ports:
      - "8990:8990"
    environment:
      - WEBSOCKET_PORT=8990
    networks:
      - htb
    volumes:
      - ./websocket:/websocket
    command: >
      sh -c "cd /websocket &&
             npm install &&
             node index.js"

  api:
    container_name: htb-api
    image: python
    environment:
      - REDIS_HOST=htb-redis
      - REDIS_PORT=6379

    ports:
      - "5000:5000"
    networks:
      - htb
    volumes:
      - ./api:/api
    command: >
      sh -c "cd /api &&
             python -m venv .venv &&
             . .venv/bin/activate &&
             pip install -r requirements.txt &&
             gunicorn -w 4 -b 0.0.0.0:5000 app.app:app"
