apiVersion: v1
data:
  .env: ""
  requirements.txt: |
    Flask
    gunicorn
    flask_cors
    werkzeug
    redis
    python-dotenv
  wsgi.py: |+
    """Web Server Gateway Interface"""

    ##################
    # FOR PRODUCTION
    ####################
    from app.app import app

    if __name__ == "__main__":

        app.run(host='0.0.0.0', debug=True)

kind: ConfigMap
metadata:
  labels:
    io.kompose.service: api
  name: api-cm1
