apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-end
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: front-end
    spec:
      containers:
        - args:
            - sh
            - -c
            - |-
              cd /htb-frontend &&
                     npm install &&
                     npm run dev -- --host
          env:
            - name: VITE_API_PORT
              value: "5000"
            - name: VITE_API_URL
              value: http://localhost
            - name: VITE_WEBSOCKET_PORT
              value: "8990"
            - name: VITE_WEBSOCKET_URL
              value: ws://localhost
          image: node
          name: htb-web
          ports:
            - containerPort: 5173
              protocol: TCP
          volumeMounts:
            - mountPath: /htb-frontend
              name: front-end-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: front-end-cm0
          name: front-end-cm0
